language: go

go:
    - 1.9

script:
    - go test $(go list ./... | grep -v /vendor/)
    - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
